version: '2'
services:
    cliv_server-app:
        image: cliv_server
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/cliv
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        network_mode: "host"
    cliv_server-postgresql:
        extends:
            file: postgresql.yml
            service: cliv_server-postgresql

