version: '2'
services:
    cliv_server-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/cliv_server/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cliv_server
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
